local Styles = {}

function Styles.GetEquippedStyleName(player, styleType)
	local override = _G.sessionData[player]["Equipped"..styleType.."LimitedStyle"]
	if override then
		return override
	end

	local slotNum = _G.sessionData[player]["Equipped"..styleType.."Style"]
	local inventory = _G.sessionData[player][styleType.."StyleInventory"]

	if slotNum and inventory and inventory[slotNum] then
		return inventory[slotNum].StyleName
	end

	return nil
end

Styles.SlotUpgrades = {
	Offensive = {
		[1] = 3363308239,
		[2] = 3363309711,
		[3] = 3363310021,
		[4] = 3363310231,
		[5] = 3541019190,
	},
	OffensiveGift = {
		[1] = 3440194394,
		[2] = 3440195819,
		[3] = 3440196355,
		[4] = 3440196853,
		[5] = 3541019618,
	},
	Defensive = {
		[1] = 3363307381,
		[2] = 3363308609,
		[3] = 3363308949,
		[4] = 3363309461,
		[5] = 3541019016,
	},
	DefensiveGift = {
		[1] = 3440194067,
		[2] = 3440194770,
		[3] = 3440196144,
		[4] = 3440196652,
		[5] = 3541019419,
	}
}

Styles.DefensiveStyles = {
	["Subzero"] = {
		Rarity = "Limited",
		Ultimate = "Snowball",
		UltimateDescription = "Throw a snowball that covers the hitter's screen",
		PitchAbilities = {"Fastball", "Riser", "Changeup", "Eephus"},
		SubType = "Pitching",
		Available = false,
	},
	["Softball"] = {
		Rarity = "Limited",
		Ultimate = "Super Toss",
		UltimateDescription = "Throw a super fast sinking pitch",
		PitchAbilities = {"Fastball", "Sinker", "Forkball", "Eephus"},
		SubType = "Pitching",
		Available = false,
	},
	["Kamehameha"] = {
		Rarity = "Superstar",
		Ultimate = "Beam Blast",
		UltimateDescription = "Creates a laser beam that distracts the hitter",
		PitchAbilities = {"Nitroball", "Slider", "Sinker", "Cutter"},
		SubType = "Pitching",
		Available = true,
	},
	["Blight"] = {
		Rarity = "Superstar",
		Ultimate = "Dirt Ball",
		UltimateDescription = "Covers the batter's view with dirt",
		PitchAbilities = {"Fastball", "Riser", "Slurve", "Splitter"},
		SubType = "Pitching",
		Available = true,
	},
	["Coverage"] = {
		Rarity = "Legendary",
		Ultimate = "Zone Cover",
		UltimateDescription = "Warp to the outfield zone closest to the ball (left, center, or right)",
		Ability = "Safe Stop",
		AbilityDescription = "Warp to the base the lead runner is advancing to",
		SubType = "Fielding",
		Available = true,
	},
	["Ascension"] = {
		Rarity = "Mythic",
		Ultimate = "Sky Fall",
		UltimateDescription = "The greatest eephus ever thrown",
		PitchAbilities = {"Fastball", "Sinker", "Riser", "Curveball"},
		SubType = "Pitching",
		Available = true,
	},
	["Meditation"] = {
		Rarity = "Mythic",
		Ultimate = "Orbit Pitch",
		UltimateDescription = "Using the power of space throw a ball that accelerates late into the pitch",
		PitchAbilities = {"Fastball", "Sinker", "Slowball", "Curveball"},
		SubType = "Pitching",
		Available = true,
	},
	["Serenity"] = {
		Rarity = "Legendary",
		Ultimate = "Calm Pitch",
		UltimateDescription = "Throws a slow pitch that doesn't travel far when hit",
		PitchAbilities = {"Fastball", "Sinker", "Changeup", "Knuckleball"},
		SubType = "Pitching",
		Available = true,
	},
	["Seismic"] = {
		Rarity = "Legendary",
		Ultimate = "Seismic Pitch",
		UltimateDescription = "Creates a rift in the earth as a fast ball is pitched",
		PitchAbilities = {"Fastball", "Slider", "Sinker", "Changeup"},
		SubType = "Pitching",
		Available = true,
	},
	["Boomerang"] = {
		Rarity = "Epic",
		Ultimate = "Boomerang Pitch",
		UltimateDescription = "Pitch a wide boomerang-like curve ball",
		PitchAbilities = {"Fastball", "Slider", "Eephus", "Splitter"},
		SubType = "Pitching",
		Available = true,
	},
	["Whirlwind"] = {
		Rarity = "Epic",
		Ultimate = "Tornado Pitch",
		UltimateDescription = "Pitch the ball in a tornado-like motion",
		PitchAbilities = {"Fastball", "Curveball", "Slider", "Sinker"},
		SubType = "Pitching",
		Available = true,
	},
	["Flamethrower"] = {
		Rarity = "Rare",
		Ultimate = "Fire Pitch",
		UltimateDescription = "Throws a faster pitch with flames on the ball",
		PitchAbilities = {"Fastball", "Curveball", "Sinker", "Changeup"},
		SubType = "Pitching",
		Available = true,
	},
	["Deceiver"] = {
		Rarity = "Rare",
		Ultimate = "Fake Ball",
		UltimateDescription = "Pitch two baseballs where one is real and one is fake",
		PitchAbilities = {"Fastball", "Changeup", "Cutter", "Splitter"},
		SubType = "Pitching",
		Available = true,
	},
	["Ghost"] = {
		Rarity = "Uncommon",
		Ultimate = "Shadow Pitch",
		UltimateDescription = "Pitch an almost invisible ball",
		PitchAbilities = {"Fastball", "Sinker", "Curveball", "Slider"},
		SubType = "Pitching",
		Available = true,
	},
	["Growth"] = {
		Rarity = "Uncommon",
		Ultimate = "Giant Ball",
		UltimateDescription = "Pitch a giant ball that shrinks upon reaching the plate",
		PitchAbilities = {"Fastball", "Curveball", "Slider", "Cutter"},
		SubType = "Pitching",
		Available = true,
	},
	["Magma"] = {
		Rarity = "Uncommon",
		Ultimate = "Fire Throw",
		UltimateDescription = "Throws a ball really fast to other fielders",
		Ability = "Fire Boots",
		AbilityDescription = "Run really fast with fiery speed (18 -> 30 speed)",
		SubType = "Fielding",
		Available = true,
	},
	["Magnetism"] = {
		Rarity = "Rare",
		Ultimate = "Super Magnet",
		UltimateDescription = "Automatically catch any ball within a 20 stud radius",
		Ability = "Small Magnet",
		AbilityDescription = "Automatically catch any ball within a 10 stud radius",
		SubType = "Fielding",
		Available = true,
	},
	["Acrobat"] = {
		Rarity = "Uncommon",
		Ultimate = "Super Jump",
		UltimateDescription = "Jump high to catch balls that would normally be unreachable",
		Ability = "Super Sprint",
		AbilityDescription = "Run fast to get to the ball quickly (18 -> 30 speed)",
		SubType = "Fielding",
		Available = true,
	},
	["Buccaneer"] = {
		Rarity = "Epic",
		Ultimate = "Player Cannon",
		UltimateDescription = "Shoot yourself out of a cannon straight to home plate!",
		Ability = "Anchor",
		AbilityDescription = "Attach and anchor to a player slowing them down.",
		SubType = "Fielding",
		Available = true,
	},
	["Poseidon"] = {
		Rarity = "Mythic",
		Ultimate = "Great Tsunami",
		UltimateDescription = "Send a tsuanmi knocking over baserunners!",
		Ability = "Trident Throw",
		AbilityDescription = "Throw the ball super fast.",
		SubType = "Fielding",
		Available = true,
	},
	["Warden"] = {
		Rarity = "Epic",
		Ultimate = "Lockdown",
		UltimateDescription = "Jail cell locks up the closest base to you for 3 seconds",
		Ability = "Chain Grab",
		AbilityDescription = "Grapple towards the closest base to you",
		SubType = "Fielding",
		Available = true,
	},
	["Fisherman"] = {
		Rarity = "Rare",
		Ultimate = "Reel",
		UltimateDescription = "Reel in a ground ball that is far away from you",
		Ability = "Fish Dive",
		AbilityDescription = "Dive even further",
		SubType = "Fielding",
		Available = true,
	},
}

Styles.OffensiveStyles = {
	["Blizzard"] = {
		Rarity = "Limited",
		Ultimate = "Frozen Swing",
		UltimateDescription = "Turns the field into ice and freezes outfielders.",
		Ability = "Balanced Accuracy",
		AbilityDescription = "Contact and Power are slightly more accurate",
		SubType = "Hitting",
		Available = false,
	},
	["Overdrive"] = {
		Rarity = "Superstar",
		Ultimate = "Overcharge",
		UltimateDescription = "Ball zig zags randomly zapping the first player to touch it",
		Ability = "Contact Swing+",
		AbilityDescription = "Contact Swing has a higher accuracy",
		SubType = "Hitting",
		Available = true,
	},
	["Shadow"] = {
		Rarity = "Superstar",
		Ultimate = "Dark Swing",
		UltimateDescription = "Ball phases in and out of reality while traveling with no landing indicator",
		Ability = "Power Swing+",
		AbilityDescription = "Power Swing is really strong but harder to land",
		SubType = "Hitting",
		Available = true,
	},
	["Harvest"] = {
		Rarity = "Mythic",
		Ultimate = "Harvest",
		UltimateDescription = "A corn field spawns slowing down fielders",
		Ability = "Power Swing+",
		AbilityDescription = "Power swing is stronger",
		SubType = "Hitting",
		Available = true,
	},
	["Firetwist"] = {
		Rarity = "Mythic",
		Ultimate = "Spin Swing",
		UltimateDescription = "Two fireballs follow the ball knocking down anyone in its path",
		Ability = "Contact Swing+",
		AbilityDescription = "Contact Swing has a higher accuracy",
		SubType = "Hitting",
		Available = true,
	},
	["Quantum"] = {
		Rarity = "Mythic",
		Ultimate = "Base Warp",
		UltimateDescription = "Instantly teleport to the next base and free to keep running after",
		Ability = "First Base",
		AbilityDescription = "Instantly teleport to first base but become locked in base until the play ends",
		SubType = "Baserunning",
		Available = true,
	},
	["Deadeye"] = {
		Rarity = "Legendary",
		Ultimate = "Test Swing",
		UltimateDescription = "WIP",
		Ability = "Power Swing+",
		AbilityDescription = "Power Swing is stronger but harder to land",
		SubType = "Hitting",
		Available = true,
	},
	["Impact"] = {
		Rarity = "Legendary",
		Ultimate = "Seismic Swing",
		UltimateDescription = "Earth spikes pop around the drop down, always a hit",
		Ability = "Power Swing+",
		AbilityDescription = "Power Swing is stronger but harder to land",
		SubType = "Hitting",
		Available = true,
	},
	["Portal"] = {
		Rarity = "Legendary",
		Ultimate = "Portal Swing",
		UltimateDescription = "Ball travels through a portal and lands on a random spot on the field",
		Ability = "Contact Swing+",
		AbilityDescription = "Contact Swing has a higher accuracy",
		SubType = "Hitting",
		Available = true,
	},
	["Whirlwind"] = {
		Rarity = "Epic",
		Ultimate = "Tornado Swing",
		UltimateDescription = "Hit a tornado ball that knocks down any defensive player on contact",
		Ability = "Contact Swing+",
		AbilityDescription = "Contact Swing has a higher chance to hit",
		SubType = "Hitting",
		Available = true,
	},
	["Gardener"] = {
		Rarity = "Epic",
		Ultimate = "Flower Swing",
		UltimateDescription = "Garden grows around the landing spot and can't be entered by a fielder",
		Ability = "Contact Swing+",
		AbilityDescription = "Contact Swing is higher but Power Swing is weaker",
		SubType = "Hitting",
		Available = true,
	},
	["Skybound"] = {
		Rarity = "Epic",
		Ultimate = "Super Boost",
		UltimateDescription = "A long speed boost lasting 6 seconds (18 -> 25 speed)",
		Ability = "Aerial Vault",
		AbilityDescription = "Perform a powerful front-flip leap that vaults over defenders and tag attempts.",
		SubType = "Baserunning",
		Available = true,
	},
	["Phaser"] = {
		Rarity = "Rare",
		Ultimate = "Untouchable",
		UltimateDescription = "Become completely intangible for 2.5 seconds to avoid tags",
		Ability = "Flicker",
		AbilityDescription = "Blink in and out of reality, creating brief windows of immunity to tags",
		SubType = "Baserunning",
		Available = true,
	},
	["Elastic"] = {
		Rarity = "Rare",
		Ultimate = "Bouncy Ball",
		UltimateDescription = "Ball bounces crazily after landing making it difficult to retrieve",
		Ability = "Contact Swing+",
		AbilityDescription = "Contact Swing is easier to land but Power Swing is weaker",
		SubType = "Hitting",
		Available = true,
	},
	["Combustion"] = {
		Rarity = "Rare",
		Ultimate = "Bomb Swing",
		UltimateDescription = "Ball turns into a bomb when hit and explodes when it lands",
		Ability = "Power Swing+",
		AbilityDescription = "Power Swing is stronger but harder to land",
		SubType = "Hitting",
		Available = true,
	},
	["Heat"] = {
		Rarity = "Uncommon",
		Ultimate = "Fire Swing",
		UltimateDescription = "Swings with fiery power to hit the ball harder",
		Ability = "Power Swing+",
		AbilityDescription = "Power Swing hits will go further",
		SubType = "Hitting",
		Available = true,
	},
	["Boomerang"] = {
		Rarity = "Uncommon",
		Ultimate = "Boomerang Swing",
		UltimateDescription = "Ball boomerangs in the air when hit, creating a fake landing indicator",
		Ability = "Contact Swing+",
		AbilityDescription = "Contact Swing is higher but Power Swing is weaker",
		SubType = "Hitting",
		Available = true,
	},
	["Slipstream"] = {
		Rarity = "Uncommon",
		Ultimate = "Super Slide",
		UltimateDescription = "Slide faster and farther than normal to steal a base",
		Ability = "Quick Boost",
		AbilityDescription = "A short speed boost lasting 3 seconds (18 -> 25 speed)",
		SubType = "Baserunning",
		Available = true,
	},
}

return Styles
